openapi: 3.0.0
tags:
  - name: account
    description: For account login logout
  - name: shop
    description: Retrieving info regarding shops
  - name: user
    description: Retrieveing info regarding users (staff)
  - name: duty
    description: Retrieveing info regarding duties of doctors
info:
  title: Asia bot api
  description: |
    Api doc for Asia bot (web admin panel). Normally except for login api, the rest of the apis require login token in the header. The tokens for mobile and admin panel are not the same.
    The error responses in this doc is not the main focus.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: hugocheung@instajs.com
    name: Hugo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'http://sallyapi.ijs.network:8080/api'
    description: Development endpoint (part of them are responsing hard-coded data)
paths:
  /admin/login:
    post:
      summary: ''
      operationId: post-admin-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    description: Admin token for the subsequent apis
                  isAdmin:
                    type: boolean
              examples:
                example-1:
                  value:
                    success: true
                    token: 190e8095-64df-4c4c-b77f-5ad8695a8e84
                    isAdmin: true
      description: Admin login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
              required:
                - user_name
                - password
            examples:
              example-1:
                value:
                  user_name: ''
                  password: ''
      tags:
        - account
  /admin/logout:
    get:
      summary: Your GET endpoint
      tags:
        - account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
      operationId: get-admin-logout
      description: Admin logout
  /shop/info:
    get:
      summary: Your GET endpoint
      tags:
        - shop
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      shops:
                        $ref: '#/components/schemas/shop_model'
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      shops:
                        - guid: 1aaf4b41-5567-4c97-96a8-967e11174187
                          pic_guid: 50cf60b1-2fe2-41a8-b66d-0e9b7567f963
                          code: '300'
                          name: Demo Clinic 3
                          district: Sham Shui Po
                          address: Sham Shui Po Fuk Wa Street
                          tel: '23232323'
                          desc: Desc desc
                          default_receiver: 50cf60b1-2fe2-41a8-b66d-0e9b7567f963
                        - guid: a32b7d3d-adcf-486e-a92a-cb6ed782bad3
                          pic_guid: 9b1b15c4-83d0-44f0-8112-104ae92939de
                          code: '700'
                          name: Demo Clinic 700
                          district: Sham Shui Po
                          address: Sham Shui Po Fuk Wa Street
                          tel: '23232366'
                          desc: Desc desc
                          default_receiver: 9b1b15c4-83d0-44f0-8112-104ae92939de
                        - guid: c0e3f345-c47c-4596-aaeb-96f212150f8a
                          pic_guid: a46d48cd-94dd-489b-8438-caab9ec5d57b
                          code: '100'
                          name: Demo Clinic 2
                          district: Sham Shui Po
                          address: Sham Shui Po Fuk Wa Street
                          tel: '23232323'
                          desc: Desc desc
                          default_receiver: a46d48cd-94dd-489b-8438-caab9ec5d57b
                        - guid: ee4c3dbc-aa7d-4e70-9bf7-bf328dc8334b
                          pic_guid: cbc303bb-4a75-480e-a5b6-c9b5453dacbd
                          code: '300'
                          name: Demo Clinic 300
                          district: Sham Shui Po
                          address: Sham Shui Po Fuk Wa Street
                          tel: '23232355'
                          desc: Desc desc
                          default_receiver: cbc303bb-4a75-480e-a5b6-c9b5453dacbd
                        - guid: 396f5b9d-1ddf-4ae2-a77c-9c34ebe14e2a
                          pic_guid: b725211c-895d-48b9-ba1a-d32ad31337b3
                          code: '200'
                          name: Demo Clinic 0
                          district: Wong Tai Sin
                          address: Mong Kok Fa Yuen Street
                          tel: '20003000'
                          desc: '20003000'
                          default_receiver: b725211c-895d-48b9-ba1a-d32ad31337b3
      operationId: get-shop-info
      description: Get all shop info
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
    post:
      summary: ''
      operationId: post-shop-info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
      description: Create shop. Must have a user guid to be the pic_guid (person-in-charge).
      tags:
        - shop
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shop_model'
            examples:
              example-1:
                value:
                  pic_guid: 9b1b15c4-83d0-44f0-8112-104ae92939de
                  code: '700'
                  name: Demo Clinic 700
                  district: Sham Shui Po
                  address: Sham Shui Po Fuk Wa Street
                  tel: '23232366'
                  desc: Desc desc
                  default_receiver: 9b1b15c4-83d0-44f0-8112-104ae92939de
    patch:
      summary: ''
      operationId: patch-shop-info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
      description: 'Edit shop. The parameters are optional, not all of them are required'
      tags:
        - shop
      parameters:
        - schema:
            type: string
          in: header
          name: token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shop_model'
            examples:
              example-1:
                value:
                  pic_guid: 9b1b15c4-83d0-44f0-8112-104ae92939de
                  code: '700'
                  name: Demo Clinic 700
                  district: Sham Shui Po
                  address: Sham Shui Po Fuk Wa Street
                  tel: '23232366'
              example-2:
                value:
                  code: '700'
                  name: Demo Clinic 700
  /shop/duty:
    get:
      summary: Your GET endpoint
      tags:
        - duty
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      duties:
                        type: array
                        items:
                          type: object
                          properties:
                            shop_name:
                              type: string
                            shop_code:
                              type: string
                            district:
                              type: string
                            address:
                              type: string
                            doctors:
                              type: array
                              items:
                                type: string
                            modify_by:
                              type: string
                            modify_date:
                              type: string
      operationId: get-shop-duty
      description: 'Get duties of all shops of certain month & year'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                duty_month:
                  type: integer
                  example: 5
                duty_year:
                  type: integer
                  example: 2020
              required:
                - duty_month
                - duty_year
            examples:
              example-1:
                value:
                  duty_month: 5
                  duty_year: 2020
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
    post:
      summary: ''
      operationId: post-shop-duty
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
      tags:
        - duty
      description: 'Assign duty for a certain shop for a certain month&year'
      parameters:
        - schema:
            type: string
          in: header
          name: login token
          description: login token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_list:
                  type: array
                  items:
                    type: string
                shop_guid:
                  type: string
                duty_month:
                  type: integer
                duty_year:
                  type: integer
              required:
                - doctor_list
                - shop_guid
                - duty_month
                - duty_year
            examples:
              example-1:
                value:
                  doctor_list:
                    - d2dc57b4-946e-4402-81a4-a98d6b2eae88
                  shop_guid: 1aaf4b41-5567-4c97-96a8-967e11174187
                  duty_month: 5
                  duty_year: 2020
components:
  schemas:
    basic_error_response:
      title: basic_error_response
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    shop_model:
      title: shop_model
      type: object
      x-tags:
        - shop
      properties:
        pic_guid:
          type: string
        code:
          type: string
        name:
          type: string
        district:
          type: string
        address:
          type: string
        tel:
          type: string
        desc:
          type: string
        default_receiver:
          type: string
      x-examples:
        example-1:
          pic_guid: 9b1b15c4-83d0-44f0-8112-104ae92939de
          code: '700'
          name: Demo Clinic 700
          district: Sham Shui Po
          address: Sham Shui Po Fuk Wa Street
          tel: '23232366'
          desc: Desc desc
          default_receiver: 9b1b15c4-83d0-44f0-8112-104ae92939de
      description: ''
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
