openapi: 3.0.0
tags:
  - name: User
    description: 'Get User profile, login'
  - name: Sop
    description: The main bot engine logic
  - name: File
    description: Handle file upload/ download via S3
info:
  title: doc2
  version: '1.0'
  contact:
    name: Hugo Cheung
    email: hugocheung@Instajs.com
  description: Api documentation mainly for mobile client
servers:
  - url: 'http://sallyapi.ijs.network:8080/api'
paths:
  /user/login:
    post:
      summary: ''
      operationId: post-user-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    description: 'login token for subsequent api calls, being inserted in the request header'
              examples:
                example-1:
                  value:
                    success: true
                    token: 2c3f70d0-4c42-4346-90a8-7d5849a2a34a
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
                device_id:
                  type: string
            examples:
              example-1:
                value:
                  user_name: invalid user name
                  password: invalid password
                  device_id: '123123'
      description: User login (mobile/ web)
      tags:
        - User
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
          required: true
  /user/profile:
    get:
      summary: Your GET endpoint
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      staff_id:
                        type: string
                      full_name:
                        type: string
                      email:
                        type: string
                      tel:
                        type: string
                      gender:
                        type: string
                      direct_line:
                        type: string
                      avatar_url:
                        type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      staff_id: '123456'
                      full_name: null
                      email: hugocheung@instajs.com
                      tel: '66667777'
                      gender: M
                      direct_line: '22223334'
                      avatar_url: null
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
      operationId: get-user-profile
      requestBody:
        content:
          application/json:
            schema: {}
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
          required: true
      description: "Get user's profile info"
    patch:
      summary: ''
      operationId: patch-user-profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
      description: "Edit user's profile"
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                staff_id:
                  type: string
                gender:
                  type: string
                email:
                  type: string
                tel:
                  type: string
                direct_line:
                  type: string
                department:
                  type: string
                avatar_url:
                  type: string
                device_id:
                  type: string
                  description: 'this field is used for push-notification, when client registered firebase token, can call this api to update it. Messages will be sent according to this field'
            examples:
              example-1:
                value:
                  staff_id: '123456'
                  gender: M
                  email: hugocheung@instajs.com
                  tel: '66667777'
                  direct_line: '22223334'
                  department: Department 1
  /sop/current:
    get:
      summary: Your GET endpoint
      tags:
        - Sop
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sop_response'
              examples:
                example-1-first time login and first time calling this api):
                  value:
                    success: true
                    data:
                      sop_type: greetings
                      message:
                        - type: text
                          content: '請問我有什麼可以幫到你?<br>申請零用現金流程<br>填寫Monthly Order Form<br>EHR'
                      action:
                        - id: start_petty_cash
                          property_id: start_petty_cash
                          sop_type: petty_cash
                          type: cart
                          image: 'https://.'
                          title: 申請零用現金流程
                          desc: ''
                          button: 填寫Petty Cash Report
                          value: start_petty_cash_report
                          next: pc25
                        - id: start_po
                          property_id: start_po
                          sop_type: po
                          type: button
                          title: 每月訂購流程
                          value: start_po
                          next: po30
                        - id: start_ehr
                          property_id: start_ehr
                          sop_type: ehr
                          type: button
                          title: 開始處理醫健通月結單
                          value: start_ehr
                          next: ehr30
                example-2:
                  value:
                    success: true
                    data:
                      start: true
                      sop_type: petty_cash
                      message:
                        - type: text
                          content: 你好，請問有咩幫到你?
                      action:
                        - id: start_petty_cash
                          property_id: start_petty_cash
                          type: button
                          title: 申請零用現金流程
                          value: 申請零用現金流程
                          next: pc25
                      id: pc20
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
      operationId: get-sop-current
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
          required: true
      description: 'Being called whenever user launch the app (with or without login session), in order to get the current sop type and the current step'
  '/sop/{sop_type}/proceed':
    parameters:
      - schema:
          type: string
        name: sop_type
        in: path
        required: true
    post:
      summary: ''
      operationId: post-sop-sop_type-proceed
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sop_response'
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      start: true
                      sop_type: petty_cash
                      message:
                        - type: text
                          content: 需要處理Travelling Expense Summary Report嗎?
                      action:
                        - id: travelling_expense_summary_handle_y
                          property_id: travelling_expense_summary_handle
                          type: button
                          title: 需要
                          value: 需要
                          next: pc30
                        - id: travelling_expense_summary_handle_n
                          property_id: travelling_expense_summary_handle
                          type: button
                          title: 不需要
                          value: 不需要
                          next: ''
                      id: pc25
                example-2:
                  value:
                    success: true
                    data:
                      sop_type: petty_cash
                      message:
                        - type: text
                          content: 現在先處理Travelling Expense Summary Report
                        - type: text
                          content: 請確認表格上的Applied By及Approved by欄上已有簽名
                      action:
                        - id: travelling_expense_summary_signature
                          property_id: travelling_expense_summary_signature
                          type: button
                          title: 已有簽名
                          value: 已有簽名
                          next: pc40
                      id: pc30
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
      description: "Proceed the sop according to user's response, mainly from clicking buttons / replying text(numbers) / sending attachments / picking date /"
      tags:
        - Sop
      parameters:
        - schema:
            type: string
          in: header
          name: token
          required: true
          description: login token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                step_id:
                  type: string
                action_id:
                  type: string
                property_id:
                  type: string
                value:
                  type: string
            examples:
              example-1:
                value:
                  step_id: pc25
                  action_id: start_petty_cash
                  property_id: start_petty_cash
                  value: 申請零用現金流程
              example-2:
                value:
                  step_id: pc30
                  action_id: travelling_expense_summary_handle_y
                  property_id: travelling_expense_summary_handle
                  value: 需要
              example-po:
                value:
                  step_id: po30
                  action_id: start_po
                  property_id: start_po
                  value: 開始每月訂購流程
  '/sop/{sop_type}/current':
    parameters:
      - schema:
          type: string
        name: sop_type
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Sop
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sop_response'
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      start: true
                      sop_type: petty_cash
                      message:
                        - type: text
                          content: 你好，請問有咩幫到你?
                      action:
                        - id: start_petty_cash
                          property_id: start_petty_cash
                          type: button
                          title: 申請零用現金流程
                          value: 申請零用現金流程
                          next: pc25
                      id: pc20
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
      operationId: get-sop-sop_type-current
      description: Triggered to call this api when the 3 sop buttons are pressed / the greeting message are pressed
      parameters:
        - schema:
            type: string
          in: header
          name: token
          required: true
          description: login token
  /user/chatHistory:
    get:
      summary: Your GET endpoint
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      total_length:
                        type: number
                      page_size:
                        type: number
                      page:
                        type: number
                      history:
                        type: array
                        items:
                          type: object
                          properties:
                            content:
                              type: string
                            chat_type:
                              type: string
                            create_date:
                              type: string
                            create_by:
                              type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      total_length: 124
                      page_size: 50
                      page: 2
                      history:
                        - content: 請選擇需要修改的項目
                          chat_type: text
                          create_date: '2020-05-21 19:05:27'
                          create_by: bot
                        - content: 請選擇需要修改的項目
                          chat_type: text
                          create_date: '2020-05-21 19:01:09'
                          create_by: bot
                        - content: 我需要修改
                          chat_type: text
                          create_date: '2020-05-21 19:01:09'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 確認寫到report?
                          chat_type: text
                          create_date: '2020-05-21 19:00:47'
                          create_by: bot
                        - content: '你已填寫travel expense的項目: Travelling Expense Summary <br>日期: {{travelling_expense_summary_date}}<br>金額: {{travelling_expense_summary_amount}}'
                          chat_type: text
                          create_date: '2020-05-21 19:00:47'
                          create_by: bot
                        - content: 確認寫到report?
                          chat_type: text
                          create_date: '2020-05-21 18:59:02'
                          create_by: bot
                        - content: '你已填寫travel expense的項目: Travelling Expense Summary <br>日期: 2020-05-21<br>金額: 500'
                          chat_type: text
                          create_date: '2020-05-21 18:59:02'
                          create_by: bot
                        - content: travelling_expense_summary_report_file_id
                          chat_type: attachment
                          create_date: '2020-05-21 18:59:02'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 請上傳本月份的Travelling Expense Summary Report
                          chat_type: text
                          create_date: '2020-05-21 18:58:16'
                          create_by: bot
                        - content: '500'
                          chat_type: text
                          create_date: '2020-05-21 18:58:16'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: Travelling Expense Summary的費用金額是
                          chat_type: text
                          create_date: '2020-05-21 18:55:00'
                          create_by: bot
                        - content: '2020-05-21'
                          chat_type: text
                          create_date: '2020-05-21 18:55:00'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: Travelling Expense Summary的日期是?
                          chat_type: text
                          create_date: '2020-05-21 18:54:35'
                          create_by: bot
                        - content: 已有簽名
                          chat_type: text
                          create_date: '2020-05-21 18:54:35'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 請確認表格上的Applied By及Approved by欄上已有簽名
                          chat_type: text
                          create_date: '2020-05-21 18:50:52'
                          create_by: bot
                        - content: 現在先處理Travelling Expense Summary Report
                          chat_type: text
                          create_date: '2020-05-21 18:50:52'
                          create_by: bot
                        - content: 需要
                          chat_type: text
                          create_date: '2020-05-21 18:50:52'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 需要處理Travelling Expense Summary Report嗎?
                          chat_type: text
                          create_date: '2020-05-21 18:46:09'
                          create_by: bot
                        - content: 申請零用現金流程
                          chat_type: text
                          create_date: '2020-05-21 18:46:09'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 你好，請問有咩幫到你?
                          chat_type: text
                          create_date: '2020-05-21 18:40:50'
                          create_by: bot
                        - content: 你好，請問有咩幫到你?
                          chat_type: text
                          create_date: '2020-05-21 18:40:32'
                          create_by: bot
                example-2(with file):
                  value:
                    success: true
                    data:
                      total_length: 138
                      page_size: 20
                      page: 0
                      history:
                        - content: 請問是否已經下載IVSS?
                          chat_type: text
                          create_date: '2020-05-26 12:52:36'
                          create_by: bot
                        - content: Okay~收到
                          chat_type: text
                          create_date: '2020-05-26 12:52:35'
                          create_by: bot
                        - content: 'https://ijs-sally-dev.s3.ap-east-1.amazonaws.com/test1.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAZ7VM3DDWOCT56H4B%2F20200526%2Fap-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200526T060548Z&X-Amz-Expires=900&X-Amz-Signature=a653a73b14c7ed914e8555d82185ca99d985de39a7a0e1946481b2bfbfd01387&X-Amz-SignedHeaders=host'
                          chat_type: attachment
                          create_date: '2020-05-26 12:52:35'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 請上傳HCV月結單
                          chat_type: text
                          create_date: '2020-05-26 12:51:51'
                          create_by: bot
                        - content: 已核對
                          chat_type: text
                          create_date: '2020-05-26 12:51:51'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 請問是否已核對HCV月結單與客戶確認書(Voucher)內容相符，並完整的保存?
                          chat_type: text
                          create_date: '2020-05-26 12:51:34'
                          create_by: bot
                        - content: 已經下載
                          chat_type: text
                          create_date: '2020-05-26 12:51:34'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 請問是否已經下載HCV？
                          chat_type: text
                          create_date: '2020-05-26 12:50:53'
                          create_by: bot
                        - content: 首先我們要先登入醫健通系統
                          chat_type: text
                          create_date: '2020-05-26 12:50:53'
                          create_by: bot
                        - content: 現在先處理Cheung Tai Man的月結單
                          chat_type: text
                          create_date: '2020-05-26 12:50:53'
                          create_by: bot
                        - content: Cheung Tai Man
                          chat_type: text
                          create_date: '2020-05-26 12:50:53'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 根據更表，本月需要處理的醫生月結單有：
                          chat_type: text
                          create_date: '2020-05-26 12:50:21'
                          create_by: bot
                        - content: 開始處理醫健通月結單
                          chat_type: text
                          create_date: '2020-05-26 12:50:21'
                          create_by: 4449da4c-4ac0-4905-8113-797f2aae4e25
                        - content: 你好，請問有咩幫到你?
                          chat_type: text
                          create_date: '2020-05-26 12:49:36'
                          create_by: bot
                        - content: 你好，請問有咩幫到你?
                          chat_type: text
                          create_date: '2020-05-26 10:27:23'
                          create_by: bot
                        - content: 你好，請問有咩幫到你?
                          chat_type: text
                          create_date: '2020-05-25 17:51:08'
                          create_by: bot
                        - content: 閣下的本月的Petty Cash Report已填報，請按以下連結查看
                          chat_type: text
                          create_date: '2020-05-25 17:47:29'
                          create_by: bot
                        - content: 閣下的本月的Petty Cash Report已填報，請按以下連結查看
                          chat_type: text
                          create_date: '2020-05-22 14:59:18'
                          create_by: bot
                        - content: 閣下的本月的Petty Cash Report已填報，請按以下連結查看
                          chat_type: text
                          create_date: '2020-05-22 14:58:44'
                          create_by: bot
                        - content: 閣下的本月的Petty Cash Report已填報，請按以下連結查看
                          chat_type: text
                          create_date: '2020-05-22 14:01:26'
                          create_by: bot
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
      operationId: get-user-chatHistory
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
        - schema:
            type: string
          in: query
          name: page_size
          description: 'Number of records returning, default 100'
        - schema:
            type: string
          in: query
          name: page
          description: page offset
      description: "Retrieving user's chat history. Should be called every time user lauching the app."
  /file/uploadToken:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                        description: The url for client side to upload the file
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      url: 'https://ijs-sally-dev.s3.ap-east-1.amazonaws.com/demo_image1.jpg?Content-Type=image%2Fjpeg&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAZ7VM3DDWOCT56H4B%2F20200525%2Fap-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200525T055755Z&X-Amz-Expires=900&X-Amz-Signature=cae606164579c1be3112a55e65e04b241391dd201cd03958ed10e2ff897d73c3&X-Amz-SignedHeaders=host'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
              examples: {}
      operationId: get-file-uploadToken
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file_name:
                  type: string
                key:
                  type: string
                  description: '(Optional) unique key for retrieving the file, default key would be the file_name'
                public_read:
                  type: string
                  description: ''
              required:
                - file_name
            examples:
              example-1:
                value:
                  file_name: demo_image1.jpg
      description: 'Api for retrieving the S3 upload token, default expiry time is 15 mins'
  /file/downloadToken:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                        description: the url to retrive the file
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      url: 'https://ijs-sally-dev.s3.ap-east-1.amazonaws.com/test1.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAZ7VM3DDWOCT56H4B%2F20200525%2Fap-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200525T061456Z&X-Amz-Expires=900&X-Amz-Signature=fabd0c42e39a2fbc071c240318f8725959be7b3c3e1e8aeb4b376fbb3d7f7c99&X-Amz-SignedHeaders=host'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error_response'
      operationId: get-file-downloadToken
      description: 'For retrieving S3 download token, default expiry time is 15 mins'
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: The unique key to the file
              required:
                - key
            examples:
              example-1:
                value:
                  key: test1.txt
        description: ''
  /user/notification:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: array
                        items:
                          type: object
                          properties:
                            message_code:
                              type: string
                            message_hk:
                              type: string
                            message_en:
                              type: string
                            sop_type:
                              type: string
                            create_date:
                              type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      message:
                        - message_code: '0002'
                          message_hk: 請提交本月份的醫健通報告
                          message_en: null
                          sop_type: ehr
                          create_date: '2020-05-26 15:28:09'
                        - message_code: '0002'
                          message_hk: 請提交本月份的醫健通報告
                          message_en: null
                          sop_type: ehr
                          create_date: '2020-05-21 18:15:12'
                        - message_code: '0001'
                          message_hk: 請提交本月份的每月訂購報告
                          message_en: null
                          sop_type: po
                          create_date: '2020-05-26 15:28:44'
                        - message_code: '0000'
                          message_hk: 請提交本月份的零用現金報告
                          message_en: null
                          sop_type: petty_cash
                          create_date: '2020-05-21 18:15:12'
                        - message_code: '0001'
                          message_hk: 請提交本月份的每月訂購報告
                          message_en: null
                          sop_type: po
                          create_date: '2020-05-21 18:15:12'
                        - message_code: '0002'
                          message_hk: 請提交本月份的醫健通報告
                          message_en: null
                          sop_type: ehr
                          create_date: '2020-05-26 15:28:44'
                        - message_code: '0002'
                          message_hk: 請提交本月份的醫健通報告
                          message_en: null
                          sop_type: ehr
                          create_date: '2020-05-26 15:34:16'
                        - message_code: '0001'
                          message_hk: 請提交本月份的每月訂購報告
                          message_en: null
                          sop_type: po
                          create_date: '2020-05-26 15:34:16'
                        - message_code: '0001'
                          message_hk: 請提交本月份的每月訂購報告
                          message_en: null
                          sop_type: po
                          create_date: '2020-05-26 15:28:09'
      operationId: get-user-notification
      description: User get all the notifications that have received before
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
          required: true
      tags:
        - User
components:
  schemas:
    sop_response:
      title: sop_response
      type: object
      x-examples:
        example-1:
          success: true
          data:
            sop_type: petty_cash
            end: true
            message:
              - type: text
                content: 閣下的本月的Petty Cash Report已填報，請按以下連結查看
            action:
              - id: view_petty_cash_report
                property_id: view_petty_cash_report
                type: cart
                image: 'https://.'
                title: 閣下的本月的Petty Cash Report已填報，請按以下連結查看
                desc: ''
                button: View
                url: 'https://docs.google.com/spreadsheets/d/1X1GZ0rsg1qGRhTEQDcaI5R1VwAhIMiMjfp9drMr72sY/edit'
                next: 'null'
      properties:
        success:
          type: string
        data:
          type: object
          properties:
            message:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  content:
                    type: string
            action:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  property_id:
                    type: string
                  type:
                    type: string
                  image:
                    type: string
                  title:
                    type: string
                  desc:
                    type: string
                  button:
                    type: string
                  url:
                    type: string
                  next:
                    type: string
                required:
                  - id
                  - property_id
                  - type
                  - next
            '':
              type: string
            end:
              type: boolean
    basic_error_response:
      title: basic_error_response
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
